---
title: "Heatmaps"
output: html_notebook
---

# R load
```{r}
suppressPackageStartupMessages({
    library("tidyverse")
    library("reticulate")
    library("ggplot2")
    library("SingleCellExperiment")
    library("scater")
    library("Seurat")
    library("SeuratDisk")
    library("zellkonverter")
  library(viridis)
})
# load('~/data/chick_miruna/08052021.RData')
# save just combined to reduce load time from Miruna's entire environment
# save(combined, file = '~/data/chick_miruna/combined_mgg_08052021.Rdata' )
load('~/data/chick_miruna/combined_mgg_08052021.Rdata')
combined

color_palette <- pals::glasbey()[1:14]
names(color_palette) <- seq(0,13, 1)
```




```{r, fig.width=9, fig.height=2}
genes <- c('SALL1','SALL3','OPN1LW','RXRG','OTX2','THRB', 'ONECUT1','ONECUT2')
counts <- combined@assays$RNA@counts[genes,]
mat <- counts %>% as_tibble(rownames = 'Gene') %>% pivot_longer(-Gene, names_to = 'BC') %>% 
  left_join(combined@meta.data %>% as_tibble(rownames = 'BC')) %>% 
  filter(cluster.condition == 'Sall1 CTRL_Sall1 CTRL') %>% 
  dplyr::select(Gene, BC, value) %>% 
      pivot_wider(values_from = value, names_from = BC)


row.names(mat) <- mat$Gene
mat <- mat %>% data.frame()
mat <- mat[,-1] 

cluster <- colnames(mat) %>% as_tibble() %>% dplyr::select(BC = value) %>% left_join(combined@meta.data %>% as_tibble(rownames = 'BC') %>% mutate(BC = gsub('-','.', BC))) %>% pull(seurat_clusters) 


conversion <- cbind(seq(0,13,1), c('PR2','PR3','restrRPC2','multiRPC1','trAC_HC','HC1','PR1','hdPR1','HC2','multiRPC2','hdPR2','hdPR3','RGC','restrRPC1')) %>% 
  as_tibble()

cluster2 <- cluster %>% enframe() %>% left_join(conversion, by = c('value' = 'V1')) %>% pull(V2)

a <- ComplexHeatmap::Heatmap(log2(mat+1), 
                        col = viridis(10),
                        column_split = cluster2,
                        cluster_columns = FALSE,
                        show_column_names = FALSE,
                        row_title = 'Control',
                        name ='log2 (counts)')
a

```



```{r, fig.width=9, fig.height=2}
counts <- combined@assays$RNA@counts[genes,]
mat <- counts %>% as_tibble(rownames = 'Gene') %>% pivot_longer(-Gene, names_to = 'BC') %>% 
  left_join(combined@meta.data %>% as_tibble(rownames = 'BC')) %>% 
  filter(cluster.condition == 'Sall1 KO15_Sall1 KO15') %>% 
  dplyr::select(Gene, BC, value) %>% 
      pivot_wider(values_from = value, names_from = BC)


row.names(mat) <- mat$Gene
mat <- mat %>% data.frame()
mat <- mat[,-1] 

cluster <- colnames(mat) %>% as_tibble() %>% dplyr::select(BC = value) %>% left_join(combined@meta.data %>% as_tibble(rownames = 'BC') %>% mutate(BC = gsub('-','.', BC))) %>% pull(seurat_clusters) 

cluster2 <- cluster %>% enframe() %>% left_join(conversion, by = c('value' = 'V1')) %>% pull(V2)

b <- ComplexHeatmap::Heatmap(log2(mat+1), 
                        col = viridis(10),
                        column_split = cluster2,
                        cluster_columns = FALSE,
                        show_column_names = FALSE,
                        row_title = 'KO15',
                        name ='log2 (counts)')
b
```


```{r, fig.width=9, fig.height=2}
counts <- combined@assays$RNA@counts[genes,]
mat <- counts %>% as_tibble(rownames = 'Gene') %>% pivot_longer(-Gene, names_to = 'BC') %>% 
  left_join(combined@meta.data %>% as_tibble(rownames = 'BC'), by = 'BC') %>% 
  filter(cluster.condition == 'Sall1 KO16_Sall1 KO16') %>% 
  dplyr::select(Gene, BC, value) %>% 
      pivot_wider(values_from = value, names_from = BC)


row.names(mat) <- mat$Gene
mat <- mat %>% data.frame()
mat <- mat[,-1] 

cluster <- colnames(mat) %>% as_tibble() %>% dplyr::select(BC = value) %>% left_join(combined@meta.data %>% as_tibble(rownames = 'BC') %>% mutate(BC = gsub('-','.', BC))) %>% pull(seurat_clusters) 

cluster2 <- cluster %>% enframe() %>% left_join(conversion, by = c('value' = 'V1')) %>% pull(V2)

c <- ComplexHeatmap::Heatmap(log2(mat+1), 
                        col = viridis(10),
                        column_split = cluster2,
                        cluster_columns = FALSE,
                        show_column_names = FALSE,
                        row_title = 'KO16',
                        name ='log2 (counts)')
c
```


